repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: poetry run black
    language: system
    types_or: [python, jupyter]
    args: [--config=./pyproject.toml]
- repo: local
  hooks:
  - id: isort
    name: isort
    entry: poetry run isort --resolve-all-configs
    language: system
    types: [python]
- repo: local
  hooks:
  - id: poetry lock
    name: poetry lock check
    entry: poetry lock --check
    pass_filenames: false
    language: system
- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: poetry run mypy
    pass_filenames: false
    language: system
    types: [python]
    args: ["--config-file=pyproject.toml", "."]
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: poetry run pylint
    language: system
    types: [python]
