seed_everything: 5000
model:
  class_path: fip.tasks.scm_learning_with_ground_truth.scm_learning_true_perm.SCMLearningTruePerm
  init_args:
    lr: 1e-4
    weight_decay: 1e-10
    d_model: 128
    dim_key: 32
    num_heads: 8
    d_feedforward: 128
    total_nodes: 2
    total_layers: 2
    dropout_prob: 0.
    mask_type: "triang"
    attn_type: "causal"
    cost_type: "dot_product"
    learnable_loss: false
    distributed: false
trainer:
  max_epochs: 1000
  accelerator: gpu
  devices: 1
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  inference_mode: false
  profiler: "simple"
early_stopping_callback:
  monitor: "val_loss"
  min_delta: 0.0001
  patience: 500
  verbose: False
  mode: "min"
best_checkpoint_callback:
  dirpath: "./outputs/"
  filename: "best_model"
  save_top_k: 1
  mode: "min"
  monitor: "val_loss"
  every_n_epochs: 1
last_checkpoint_callback:
  save_last: true
  save_top_k: 0  # only the last checkpoint is saved
