name: Causica CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

    - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
      id: setup-python
      with:
        python-version: "3.10"

    # The cached virtualenv links to the runner's Python, so it is only reusable with the same patch version.
    - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
      id: cache

    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: |
        poetry env use 3.10
        poetry install --extras seaborn
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Verify pre-commit checks
      uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0
      with:
        extra_args: --all-files

    - name: Test with pytest
      run: poetry run python -m pytest ./test
